name: Build And Push On Release

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      CPU_IMAGE_NAME: ghcr.io/${{ github.repository }}/cpu
      CUDA_IMAGE_NAME: ghcr.io/${{ github.repository }}/cuda
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push cpu
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.cpu
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.CPU_IMAGE_NAME }}:${{ env.IMAGE_TAG }},${{ env.CPU_IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.CPU_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.CPU_IMAGE_NAME }}:buildcache,mode=max
      
      - name: Build and push cuda
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.cuda
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.CUDA_IMAGE_NAME }}:${{ env.IMAGE_TAG }},${{ env.CUDA_IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.CUDA_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.CUDA_IMAGE_NAME }}:buildcache,mode=max